//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Demo.Dal
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WCF_Demo.Dal")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescribeField;
        
        private string NameField;
        
        private string PasswordField;
        
        private System.Nullable<System.DateTime> SubmitTimeField;
        
        private int UserIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Describe
        {
            get
            {
                return this.DescribeField;
            }
            set
            {
                this.DescribeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmitTime
        {
            get
            {
                return this.SubmitTimeField;
            }
            set
            {
                this.SubmitTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAdd")]
public interface IAdd
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdd/DoWork", ReplyAction="http://tempuri.org/IAdd/DoWorkResponse")]
    void DoWork(WCF_Demo.Dal.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdd/DoWork", ReplyAction="http://tempuri.org/IAdd/DoWorkResponse")]
    System.Threading.Tasks.Task DoWorkAsync(WCF_Demo.Dal.User user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAddChannel : IAdd, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AddClient : System.ServiceModel.ClientBase<IAdd>, IAdd
{
    
    public AddClient()
    {
    }
    
    public AddClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AddClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AddClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AddClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void DoWork(WCF_Demo.Dal.User user)
    {
        base.Channel.DoWork(user);
    }
    
    public System.Threading.Tasks.Task DoWorkAsync(WCF_Demo.Dal.User user)
    {
        return base.Channel.DoWorkAsync(user);
    }
}
